language: node_js
node_js:
    - "6"
    - "8"

services:

matrix:
    allow_failures:
#       - node_js: "5.0"

after_success:
    - npm install istanbul codecov
    - NODE_ENV=cov ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov

sudo: false
